import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthUserProvider } from "./context/AuthUserContext";
import { DatabaseProvider } from "./context/DatabaseContext";
import Header from "./components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bookmark It!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthUserProvider>
          <DatabaseProvider>
            <Header />
            {children}
          </DatabaseProvider>
        </AuthUserProvider>
      </body>
    </html>
  );
}
